[global]
log_level = 'info'

[mode]
clients.enabled = true
connections.enabled = true
channels.enabled = true
packets.enabled = true

[[chains]]
id = 'tokenchain-testnet-1'
rpc_addr = 'https://rpc.testnet.tokenchain.tokentap.ca'
grpc_addr = 'http://grpc.testnet.tokenchain.tokentap.ca:9090'
websocket_addr = 'wss://rpc.testnet.tokenchain.tokentap.ca/websocket'
account_prefix = 'tokenchain'
key_name = 'tokenchain-relayer'
store_prefix = 'ibc'
default_gas = 300000
gas_multiplier = 1.3
max_gas = 1500000
max_msg_num = 30
max_tx_size = 180000
clock_drift = '10s'
max_block_time = '20s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }

# Add peer chain entries here (e.g. osmosis testnet) when channel setup begins.
